name: Deploy Docusaurus

on:
  push:
    branches:
      - docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurando Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # ou a versão do Node.js que você usa

      - name: Instalar dependências
        run: npm install

      - name: Build do Docusaurus
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
